@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US04

autonumber

actor "Human Resources\n Manager" as Employee
participant ":System" as System

activate Employee

   loop
        Employee -> System : asks to assign skills to a collaborator
            activate System

        System --> Employee : request skill name
       deactivate System
   end
   Employee -> System : terminates task
       activate System

           System --> Employee : shows skills linked to a collaborator and ask confirmation
       deactivate System

       Employee -> System : confirms data
       activate System

           System --> Employee : display success message
       deactivate System


    deactivate System
@enduml