@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class CreateJobController {
    + CreateJobController(possibly skillRepository)
    + validateJobData(jobName, jobDescription)

}


class CreateJobUI {
    +requestData(jobName, jobDescription)
}


class Employee{
    -name:String
    -birthdate:Date
    -admissionDate:Date
    -address
    -mobileContact:String
    -emailContact:String
    -IDdocType:String
    -IDnumber:String
    -taxNumber:String
    -job:Job

}

class Collaborator {
    -listOfSkill:List<Job>
}

class Organization {
    +createSkill(skillName, skillDescription)
    +createJob(jobName, jobDescription)
}



class Job {
    -jobName:String
    -jobDescription:String

    +Job(jobName, jobDescription)
    +validateJobData(jobName, jobDescription)
}

CreateJobUI .> CreateJobController
Employee "1" ---> "1" Job : has a
CreateJobController -->  Organization : createJob
Organization .> Job : createJob
Collaborator --> Employee : is a

@enduml