@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

actor "Human Resource Manager" as HRM
participant ":CreateJobUI" as UI
participant ":CreateJobController" as CTRL
participant ":Repositories" as REPO_SINGLETON



participant "repositories\n:Repositories" as GEN_REPO_INSTANCE


participant "jobRepository:\nJobRepository" as JOB_REPO_INSTANCE
participant ":Job" as JOB
'participant ":HRManager" as MNGR


note right of REPO_SINGLETON
    - Singleton is
    in use
end note



activate HRM

        HRM -> UI : asks to create a new Job

        activate UI
            'create CTRL
            UI -> CTRL** : create

            activate CTRL

                CTRL -> REPO_SINGLETON : getInstance()

                activate REPO_SINGLETON

                    REPO_SINGLETON --> CTRL : repositories

                deactivate REPO_SINGLETON

                CTRL -> GEN_REPO_INSTANCE : getJobRepository()

                activate GEN_REPO_INSTANCE

                    GEN_REPO_INSTANCE --> CTRL : jobRepository

                deactivate GEN_REPO_INSTANCE

            deactivate CTRL


            'requests the HRM to input data
            UI --> HRM : requestData (jobName, jobDescription)
        deactivate UI

        HRM -> UI : types requested data

        activate UI

            UI -> UI : validateJobData(jobName, jobDescription)

            note right of UI
            - This kind of validation consists only in
            ensuring that the correct data type (characters only)
            is inserted.
            end note

            deactivate CTRL

            UI --> HRM : shows job data and requests confirmation

        deactivate UI

            HRM -> UI : confirms data

        activate UI

            UI -> CTRL : createJob(jobName, jobDescription)

            activate CTRL

                CTRL -> CTRL : getEmployeeFromSession()
                note right of CTRL
                    - This method will get the current logged-in HRM.
                    - The returned object (of type Employee) will be
                    argument of the next method as the creator.
                    - Explained in more detail in a partial diagram.
                end note

                |||

                CTRL -> JOB : Job(jobName, jobDescription, creator)

                activate JOB

                JOB --> CTRL : newJob

                deactivate JOB

                CTRL -> JOB_REPO_INSTANCE : add(newJob)

                activate JOB_REPO_INSTANCE

                    JOB_REPO_INSTANCE -> JOB_REPO_INSTANCE : validateJob(newJob)

                    note right of JOB_REPO_INSTANCE
                    - Explained in more detail
                    in a partial diagram.
                    end note

                    JOB_REPO_INSTANCE --> CTRL : newJob

                deactivate JOB_REPO_INSTANCE

            CTRL --> UI : newJob


        deactivate CTRL

        UI -> HRM : displays operation success

    deactivate UI

deactivate HRM

@enduml