@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "jobRepository:\nJobRepository" as JOB_REPO_INSTANCE



autonumber 16
-> JOB_REPO_INSTANCE : validateJob(newJob)

autonumber 16.1
activate JOB_REPO_INSTANCE
    group Validate Job

        JOB_REPO_INSTANCE -> JOB_REPO_INSTANCE: !contains(newJob)

    end

    autonumber 17
    <-- JOB_REPO_INSTANCE : true
deactivate JOB_REPO_INSTANCE


@enduml