@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class ListVehiclesPendingMaintenancesUI {
    +run()
    +requestData(teamMinSize, teamMaxSize, skills)
    +submitData()
}

class ListVehiclesPendingMaintenancesController{
+ListVehiclesPendingMaintenancesController()
}

class Repositories{
}

ListVehiclesPendingMaintenancesUI ..> ListVehiclesPendingMaintenancesController

ListVehiclesPendingMaintenancesController --> Repositories

@enduml