@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Vehicle Fleet Manager" as ADM
participant ":ListVehiclesPendingMaintenanceUI" as UI
participant ":ListVehiclesPendingMaintenanceController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "vehiclesRepository\n:vehiclesRepository" as VehiclesRepository

note right of singleton
    - Singleton is
    in use
end note

activate ADM

        ADM -> UI :asks to list vehicle's in need for a check-up

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : create

            UI -> CTRL : getVehiclesPendingMaintenanceList()
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getVehiclesRepository()
                activate PLAT

                    PLAT --> CTRL: vehiclesRepository
                deactivate PLAT

                CTRL -> VehiclesRepository : getVehiclesPendingMaintenance()
                activate VehiclesRepository

                    VehiclesRepository --> CTRL : vehiclesPendingMaintenanceList
                deactivate VehiclesRepository

                CTRL --> UI : vehiclesPendingMaintenanceList
            deactivate CTRL

            UI --> ADM : shows  vehicle's in need for a check-up
        deactivate UI

deactivate ADM

@enduml