@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

actor "Human Resource Manager" as HRM
participant ":CreateAssignSkillslUI" as UI
participant ":CreateSkillController" as controller
participant ":Repositories" as singleton



participant "repositories\n:Repositories" as rep


participant "SkillRepository:\nEmployeeRepository" as skillRep
participant "EmployeeRepository:\nEmployeeRepository" as employeeRep
participant ":Employee" as Employee

activate HRM

        HRM -> UI : asks for a list of employees

        activate UI
            'create CTRL
            UI -> controller** : create

            activate controller

                  controller -> singleton : getInstance()

                activate singleton

                    singleton --> controller : repositories

                deactivate singleton

                controller -> rep : getEmployeeRepository()

                activate rep

                    rep --> controller : EmployeeRepository

                deactivate rep
                    controller --> employeeRep : getAllEmployees()
                    employeeRep --> controller : getAllEmployees()
                    controller --> UI: getAllEmployees()


            deactivate controller


            'requests the HRM to input data
            UI --> HRM : shows list of employees


        HRM -> UI : selects employee



            UI -> controller : asks for list of skills

           deactivate UI
            activate controller

            controller --> skillRep : getAllSkills()
            skillRep --> controller : getAllSkills()
            controller --> UI : getAllSkills()
            activate UI

            UI --> HRM : shows list of skills


            HRM --> UI : selects skills

            Ui --> UI : validates data

           UI --> HRM : shows data

           HRM --> UI :confirms data

           UI --> controller : employeeWithSkills
deactivate UI


deactivate HRM

@enduml