 @startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US29

autonumber

actor "Collaborator" as Collaborator
participant ":System" as System

activate Collaborator

    Collaborator -> System : Asks to record the completion of a task
    activate System

        System --> Collaborator : Shows the Agenda tasks that have not yet been completed\n in which the employee is part of the team
    deactivate System

    Collaborator -> System : Selects the Agenda Entry
    activate System

        System --> Collaborator : Shows the selected tasks and requests confirmation
    deactivate System

    Collaborator -> System : Confirms data
    activate System

        System --> Collaborator : Displays operations success message
    deactivate System


@enduml