@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US20

autonumber

actor "Green Space\nManager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to register a green space
        activate System

            System --> Employee : requests data (name, area, classification, manager)
        deactivate System

        Employee -> System : types requested data
        activate System

            System --> Employee : validates data, shows green space data and requests confirmation
        deactivate System

        Employee -> System : confirms data
        activate System

            System --> Employee : displays operation success
        deactivate System

@enduml