@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model

class GreenSpaceManager {

}

class Manager {
    section
}

Manager "1" -- "*" Vehicle: creates/manages >
Manager "1" --up "1..*" GreenSpaceManager: is a >


@enduml