@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model

class GreenSpaceManager {
}

class Manager {
    section
}

class Employee {
}

class ToDoList{
    pendingTasks
}

class Entry{
    greenSpace
    task
    urgencyDegree
    approximateExpectedDuration
}

class Task {
    park
    taskType
    taskDescription
    priority
    status
}

Manager "1..*" -- "1..*" Employee: is a >
Manager "1" -- "*" Task: creates >
Manager "1" -- "*" ToDoList: manages >
Manager "1" --up "1..*" GreenSpaceManager: is a >
Entry "1..*" -- "1..*" ToDoList: has <
Task "1..*" -- "1..*" Entry
@enduml