@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US28

autonumber

actor "Collaborator" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to consult a list of tasks assigned to me
    activate System

        System --> Employee : request data (inicialDate, finalDate)
    deactivate System

    Employee -> System : types requested data
    activate System

        System --> Employee : requests confirmation
    deactivate System

    Employee -> System : confirms data and request list
    activate System

        System --> Employee : displays list of tasks
    deactivate System

@enduml