@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US27

autonumber

actor "Green Spaces\nManager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks for a list of the green spaces managed by me
    activate System

        System --> Employee : presents a list of all green spaces managed by me
    deactivate System

@enduml