@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class CreateSkillController {
    + CreateSkillController(skillRepository)
    + validateSkillData(skillName, skillDescription)
    + addSkillToRepo(newSkill)

}


class CreateSkillUI {
    +run()
    +requestData(skillName, skillDescription)
}


class Employee{
    -name:String
    -birthdate:Date
    -admissionDate:Date
    -address
    -mobileContact:String
    -emailContact:String
    -IDdocType:String
    -IDnumber:String
    -taxNumber:String
    -job:Job

    +Employee (String nome,LocalDate dateOfBirth,\nLocalDate admissionDate, String morada, int telemovel,\nString email, String idDocType, int docTypeNumber,\nint taxPayerIdNumber, String role, Job job)
}

class Repositories{
    - instance:Repositories
    - skillRepository:SkillRepository
    - jobRepository:JobRepository
    - employeeRepository:EmployeeRepository


    + getInstance()
    + getSkillRepository()
    + getJobRepository()
    + getEmployeeRepository()
}

class SkillRepository{
    + createSkill(skillName, skillDescription)
    + validateSkill(newSkill)
    + addSkill(newSkill)
}

class Skill {
    -skillName:String
    -skillDescription:String

    +Skill(skillName, skillDescription)
    +validateSkillData(skillName, skillDescription)
}

CreateSkillUI ..> CreateSkillController

CreateSkillController -->  Repositories : getInstance
Repositories ..> SkillRepository : create
SkillRepository ..> Skill : createSkill
Employee --> Skill : has a set of

@enduml
