@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

actor "Human Resource Manager" as HRM
participant ":CreateSkillUI" as UI
participant ":CreateSkillController" as CTRL
participant ":Repositories" as REPO_SINGLETON



participant "repositories\n:Repositories" as GEN_REPO_INSTANCE


participant "skillRepository:\nSkillRepository" as SKILL_REPO_INSTANCE
participant ":Skill" as SKILL
'participant ":HRManager" as MNGR


note right of REPO_SINGLETON
    - Singleton is
    in use
end note



activate HRM

        HRM -> UI : asks to create a new Skill

        activate UI
            'create CTRL
            UI -> CTRL** : create

            activate CTRL

                CTRL -> REPO_SINGLETON : getInstance()

                activate REPO_SINGLETON

                    REPO_SINGLETON --> CTRL : repositories

                deactivate REPO_SINGLETON

                CTRL -> GEN_REPO_INSTANCE : getSkillRepository()

                activate GEN_REPO_INSTANCE

                    GEN_REPO_INSTANCE --> CTRL : skillRepository

                deactivate GEN_REPO_INSTANCE

            deactivate CTRL


            'requests the HRM to input data
            UI --> HRM : requestData (skillName, skillDescription)
        deactivate UI

        HRM -> UI : types requested data

        activate UI

            UI -> UI : validateSkillData(skillName, skillDescription)



            deactivate CTRL

            UI --> HRM : shows skill data and requests confirmation

        deactivate UI

            HRM -> UI : confirms data

        activate UI

            UI -> CTRL : createSkill(skillName, skillDescription)

            activate CTRL

                CTRL -> CTRL : getEmployeeFromSession()


                |||

                CTRL -> SKILL : Skill(skillName, skillDescription, creator)

                activate SKILL

                SKILL --> CTRL : newSkill

                deactivate SKILL

                CTRL -> SKILL_REPO_INSTANCE : add(newSkill)

                activate SKILL_REPO_INSTANCE

                    SKILL_REPO_INSTANCE -> SKILL_REPO_INSTANCE : validateSkill(newSkill)


                    SKILL_REPO_INSTANCE --> CTRL : newSkill

                deactivate SKILL_REPO_INSTANCE

            CTRL --> UI : newSkill


        deactivate CTRL

        UI -> HRM : displays operation success

    deactivate UI

deactivate HRM

@enduml