@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

actor "Human Resource Manager" as HRM
participant ":CreateSkillUI" as UI
participant ":CreateSkillController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "skillRepository:\nSkillRepository" as SkillRepository
participant ":Skill" as SKILL
'participant ":HRManager" as MNGR

activate HRM

        HRM -> UI : asks to create a new Skill

        activate UI
            'create CTRL
            UI -> CTRL** : create

            activate CTRL

                CTRL -> RepositorySingleton : getInstance()

                activate RepositorySingleton

                    RepositorySingleton --> CTRL : repositories

                deactivate RepositorySingleton

                CTRL -> PLAT : getSkillRepository()

                activate PLAT

                    PLAT --> CTRL : skillRepository

                deactivate PLAT

            deactivate CTRL


            'requests the HRM to input data
            UI --> HRM : requestData (skillName, skillDescription)
        deactivate UI

        HRM -> UI : types requested data

        activate UI

            UI -> UI : validateSkillData(skillName, skillDescription)

            UI -> CTRL : validateSkill(skillName, skillDescription)
            activate CTRL


                CTRL -> SKILL : createSkill(skillName, skillDescription)

                activate SKILL

                    SKILL --> CTRL : newSkill

                deactivate SKILL

                CTRL -> SkillRepository : validateSkill(newSkill)

                activate SkillRepository

                    SkillRepository --> CTRL : true

                deactivate SkillRepository

            CTRL --> UI : newSkill

            deactivate CTRL

                UI -> HRM : validates data, shows skill data and requests confirmation



        deactivate UI


    HRM -> UI : confirms data
    activate UI

        UI -> CTRL : addSkillToRepo(newSkill)

        activate CTRL


            CTRL -> SkillRepository : addSkillToRepo(newSkill)

            activate SkillRepository

                SkillRepository -> SkillRepository : addSkill(newSkill)

                SkillRepository -> CTRL : addedSkill

            deactivate SkillRepository

            CTRL -> UI : addedSkill

        deactivate CTRL

        UI -> HRM : displays operation success

    deactivate UI

deactivate HRM

@enduml