@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US08

autonumber

actor "GreenSpace\nManager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to add an entry to the agenda
    activate System

    System --> Employee : shows list of entries and asks to select one
    Employee -> System : selects an entry
    System --> Employee : asks to select a date
    Employee -> System : select date
    System --> Employee : asks to select a starting hour
    Employee -> System : sects starting hour
    System --> Employee : shows data and asks for confirmation
    Employee -> System : confirms data
    System --> Employee : display success message

   deactivate System

@enduml