@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US08

autonumber

actor "GreenSpace\nManager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to add an entry to the agenda
    activate System

    System --> Employee : shows list of parks managed by the GSM
    Employee -> System : selects a park
    System --> Employee : shows list of task from the to-do list
    Employee -> System : selects a task
    System --> Employee : Asks to select an urgency degree
    Employee -> System : selects urgency degree
    System --> Employee : asks to type the duration
    Employee -> System : types duration
    System --> Employee : display success message

   deactivate System

@enduml