@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

actor "Green Spaces Manager" as GSM
participant ":CreateEntryToAgendaUI" as UI
participant ":CreateEntryController" as controller
participant ":Repositories" as singleton
participant "repositories\n:Repositories" as rep
participant "AgendaRepository\n:AgendaRepository" as agendaRep
participant "toDoListRepository\n:ToDoListRepository" as toDoListRep
participant "authenticationRepository\n:AuthenticationRepository" as AUTH_REPO
participant "userSession\n:UserSession" as USR_SESSION
participant ":Manager" as manager
participant ":Entry" as Entry



note right of singleton
    - Singleton is
    in use
end note

        activate GSM

        GSM -> UI : asks to add an entry to the agenda
        activate UI
            'create controller
        UI -> controller** : create
        activate controller

        controller-> singleton : getInstance()
        activate singleton

        singleton --> controller : repositories
        deactivate singleton

        controller -> singleton : getManagerFromSession()


        activate singleton

        singleton --> controller : manager

        deactivate singleton




        controller -> rep : getTodoListRepository()
        activate rep

        rep --> controller : toDoListRep
        deactivate rep

        controller -> toDoListRep : getAllEntries()
        activate toDoListRep

        toDoListRep --> controller : entries
        deactivate toDoListRep


        controller --> UI : entries
        deactivate controller

        UI --> GSM : shows list of entries and asks to select one


        GSM -> UI : selects entry

        UI --> GSM: asks to select a date
        UI -> UI : validates date
        GSM -> UI : select date for entry

        UI --> GSM : asks to type the starting hour
        UI -> UI : Validates the starting hour
        GSM -> UI : types starting hour




        UI --> GSM : shows data

                UI -> controller : asks to add new entry
                deactivate UI
                activate controller

                controller -> Entry : addNewEntry()
                activate Entry
                Entry -> Entry : validates
                Entry --> controller : newEntry
                deactivate Entry

                controller --> UI : newEntry
                activate UI

                UI --> GSM : asks for confirmation
                GSM -> UI : confirms data

                UI -> controller : add new Entry
                controller -> agendaRep : addNewEntryToAgenda()
                activate agendaRep

                agendaRep -> controller: newEntryToAgenda
                deactivate agendaRep
                controller --> UI : newEntryToAgenda
                deactivate controller
                UI -> GSM : displays success message




        deactivate UI

        deactivate GSM

@enduml