@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US05

autonumber

actor "Human Resources\nManager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to generate a team proposal
    activate System

        System --> Employee : requests team max size
    deactivate System

    Employee -> System : types requested data
    activate System

        System --> Employee : shows list of skills for the HRM to choose
    deactivate System

    Employee -> System : selects wanted skills
        activate System

    System --> Employee : shows team generated and requests confirmation
        deactivate System

    alt accept proposal

    Employee -> System : confirms team
    activate System

        System --> Employee : displays operation success and presents the team generated
    deactivate System

    end

    alt reject proposal

    Employee -> System : rejects team
        activate System

            System --> Employee : generates a new team and asks for validation
        deactivate System
    Employee -> System : accepts or rejects team
        activate System

            System --> Employee : displays message
        deactivate System

    end

@enduml