@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Human Resources\nManager" as HRM
participant ":System" as System

activate HRM

    HRM -> System : asks to create a new job
    activate System

        System --> HRM : requests data (i.e. job name, job description)
    deactivate System

    HRM -> System : types requested data
    activate System

        System --> System : validates data
    deactivate System

        System --> HRM : shows job data and requests confirmation
    deactivate System

    HRM -> System : confirms data
    activate System

        System --> HRM : displays operation success
    deactivate System

@enduml