@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

title Domain Model

class Organization {
    name
    vatNumber
    website
    phoneNumber
    email
}

class Employee {
    name
    email
    phone
}

class Collaborator {
    name
    birthdate
    admissionDate
    address
    mobileContact
    emailContact
    IDdocType
    IDnumber
    job
    skills

}

class Manager {
    section
}

class Skill {
    skillName
    skillDescription
}

class Job {
    jobName
    jobDescription
}

class Vehicle {
    plateNumber
    brand
    model
    type
    tare
    grossWeight
    currentKm
    registerDate
    acquisitionDate
    maintenanceFrequency
}

class Equipment {
    equipmentName - to be confirmed
    equipmentDescription - to be confirmed
}

class Calendar {
    pendingTasks
}


class Tasks {
    reference
    taskDescription

}

class Teams {
    teamMembers
}

class Parks {
    location
}

class Portal {
    httpAddress
}

class User {
    name
    email
    password
}

class Reports {
    type
    date
    park

}

class Comments {
    commentDescription
}

class ReportFaults {
    faultsDescription
}

class Malfunctions {
    malfunctionDescription
}



Manager "1..*" --up "1..*" Employee: is a >
Manager "1" -up "1" Portal: manages >
Manager "1" --right "1..*" Job: registers >
Manager "1" --right "*" Skill: registers >
Manager "1" --right "1..*" Collaborator: registers >
Manager "1" ---- "1" Calendar: manages >
Manager "1" --- "*" Equipment: registers >
Manager "1" -- "*" Vehicle: creates/manages >
Manager "1" --left "*" Tasks: creates >
Manager "1" -- "*" Teams: manages >




User "1..*" - "*" Parks: uses >
User "*" ----up "*" Reports: makes >

Comments "1" -- "1" Reports: are >
ReportFaults "1" -- "1" Reports: are >
Malfunctions "1" -- "1" Reports: are >

Teams "1" - "1" Parks: performs tasks in >
Teams "1" - "1" Tasks: performs >


Organization "1" -left "*" Parks: manages >
Organization "1" -- "1..*" Employee : has >


Employee "1..*" -- "1..*" Collaborator: is a >

Collaborator "1" --- "1" Job: has a >
Collaborator "1" --down "*" Skill: is assigned to <
Collaborator "1..*" --down "1" Teams: integrates >



Vehicle "1..*" - "1" Tasks: is attributed to >

Equipment "1..*" -left "1" Tasks: is attributed to >

Calendar "1" -left "*" Tasks: has >


Tasks "1..*" -- "1..*" Parks: are performed in >



Reports "*" -- "1" Portal: are submitted >

@enduml