@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative Two

autonumber

actor "Fleet \nManager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to create a new vehicle's check up
    activate System

        System --> Employee : show list of vehicle's
    deactivate System

    Employee -> System : select vehicle
    activate System

        System --> Employee : shows data from vehicle
    deactivate System

    Employee -> System : type check up data
    activate System

        System --> Employee : shows all data and requests confirmation
    deactivate System

    Employee -> System : confirms data
    activate System

        System --> Employee : displays operation success and show next check up KM
    deactivate System

@enduml