@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "Human Resources Manager" as HRM
participant "CreateEmployeeUI:\nCreateEmployeeUI" as UI


group Validate Skill
activate HRM

autonumber 19

 HRM --> UI: (selects skill)

autonumber 19.1
activate UI


        UI -> UI: (validates(skill)



    UI --> HRM: (showsNewValidatedSkills)
deactivate HRM
  end

@enduml