@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class CreateVehicleUI {
    +run()
    +requestData(brand, model, type, tare weight, \ngross weight, current km,register date, \nacquisition date, maintenance frequency, \nplate number, passengers number,\ndoors number, fuel type, trailer machines)
    +submitData()
    +requestBrand()
    +requestModel()
    +requestType()
    +requestTareWeight()
    +requestGrossWeight()
    +requestCurrentKM()
    +requestRegisterDate()
    +requestAcquisitionDate()
    +requestMaintenanceFrequency()
    +requestPlateNumber()
    +requestPassengersNumber()
    +requestDoorsNumber()
    +requestFuelType()
    +requestTrailerMachines()
}

class CreateVehicleController {
    - vehicleRepository:VehicleRepository
    - authenticationRepository:AuthenticationRepository

    - getEmployeeFromSession()
    + CreateVehicleController(vehicleRepository)
    + createVehicle(brand, model, type, tare weight, \ngross weight, current km,register date, \nacquisition date, maintenance frequency, \nplate number, passengers number,\ndoors number, fuel type, trailer machines)
}

class Employee{
    -name:String
    -birthdate:Date
    -admissionDate:Date
    -address
    -mobileContact:String
    -emailContact:String
    -IDdocType:String
    -IDnumber:String
    -taxNumber:String
    -job:Job

    +Employee (String nome,LocalDate dateOfBirth,\nLocalDate admissionDate, String morada, int telemovel,\nString email, String idDocType, int docTypeNumber,\nint taxPayerIdNumber, String role, Job job)
}

class Repositories{
    - instance:Repositories
    - skillRepository:SkillRepository
    - jobRepository:JobRepository
    - employeeRepository:EmployeeRepository
    -authenticationRepository:AuthenticationRepository


    + getInstance()
    + getSkillRepository()
    + getJobRepository()
    + getEmployeeRepository()
    + getAuthenticationRepository()
}

class VehicleRepository{
    + getVehicles()
    + validateVehicle(newVehicle)
    + addVehicle(newVehicle)
}

class AuthenticationRepository{
    + getEmployeeFromSession()
}

class Vehicle {
    - String brand
    - String model
    - String type
    - Integer tareWeight
    - Integer grossWeight
    - Integer currenteKm
    - Date registerDate
    - Date acquisitionDate
    - Integer maintenanceFrequency
    - String plateNumber
    - Integer passengersNumber
    - Integer doorsNumber
    - String fuelType
    - Boolean trailerMachines

    + Vehicle(brand, model, type, tare weight, \ngross weight, current km,register date, \nacquisition date, maintenance frequency, \nplate number, passengers number,\ndoors number, fuel type, trailer machines)
}

CreateVehicleUI "1" ..> "1" CreateVehicleController

CreateVehicleController "1" --> "1" Repositories : getInstance

Repositories "1" ..> "1" VehicleRepository : create

CreateVehicleController --> Employee : createVehicle
CreateVehicleController "1" --> "1" AuthenticationRepository : getCurrentUserSession


Employee "1" --> "*" Vehicle : createNewVehicle

CreateVehicleController --> VehicleRepository: add

@enduml