@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class PostponeAgendaEntryController {
    +getEntriesFromAgendaStartingFrom(currentDate, status)
}


class PostponeAgendaEntryUI {
    +run()
}


class Repositories{
    - instance : Repositories
    - Repository : SkillRepository
    - agendaRepository : AgendaRepository
    - employeeRepository : EmployeeRepository

    + getInstance() : Repositories
    + getAgendaRepository()
    + getEmployeeRepository()
}

class AgendaRepository{

}

class VehicleRepository{

}

class AuthenticationRepository{
    + getEmployeeFromSession()
}

class Entry {

}

class Vehicle {

}

class Employee {

}


PostponeAgendaEntryUI "1" ..> "1" PostponeAgendaEntryController




Repositories -> Repositories : instance
Repositories "1" .> "1" AgendaRepository
Repositories "1" .> "1" VehicleRepository
Repositories "1" .> "1" AuthenticationRepository

AgendaRepository --> Entry
VehicleRepository --> Vehicle


PostponeAgendaEntryController -> AgendaRepository
PostponeAgendaEntryController -> VehicleRepository
PostponeAgendaEntryController "1" ..> "1" Repositories : repositories
PostponeAgendaEntryController "1" -> "1" AuthenticationRepository : getCurrentUserSession

PostponeAgendaEntryController -> Employee

AuthenticationRepository --> Employee

Employee -> Entry
Employee -> Vehicle

@enduml