@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

class Collaborator {
    name
    birthdate
    admissionDate
    address
    mobileContact
    emailContact
    IDdocType
    IDnumber
    job
    skills

}

class Manager {
    section
}

class Skill {
    skillName
    skillDescription
}
Manager "1" --right "*" Skill: registers >
Manager "1" --right "1..*" Collaborator: registers >
Collaborator "1" --down "*" Skill: has a set of >
@enduml