@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}
class Manager {
    section
 }
class Collaborator {
    job
    skills
}
class Skill {
    skillName
    skillDescription
}
Manager "1" -- "1" Collaborator: register a >

'Employee "0..1" -- "1" User: acts as >
Task "*" - "1" Category: cataloged as >
@enduml