@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
'skinparam shadowing false

skinparam rectangle{
    BorderColor white

}

title Sprint B

left to right direction

rectangle "System Actors" as actors {
    actor "Software Quality Assessment Team Manager" as QAM
    actor "Green Space Manager" as GSM
    actor "Fleet Manager" as FM
    actor "Human Resource Manager" as HRM

}




rectangle "Use Cases" as usecases{

    usecase "US14 - Run tests for inputs of variable size, to observe execution time of US13 algorithm." as UC14
    usecase "US13 - Obtain optimal pipeline routes" as UC13
    usecase "US12 - Import pipeline data from .csv file" as UC12
    usecase "US11 - Obtain age group usage of a urban park" as UC11
    usecase "US10 - Obtain user's preferences concerning equipment of a urban park" as UC10
    usecase "US09 - Obtain the exact costs referring to water consumption of a specific green space" as UC09
    usecase "UC08 - List vehicles with pending maintenances" as UC08
    usecase "UC07 - Register vehicle maintenance" as UC07
    usecase "UC06 - Register Vehicle" as UC06
    usecase "UC05 - Generate team proposal automatically" as UC05
    usecase "UC04 - Assign Skills to a Collaborator" as UC04
    usecase "UC02 - Register jobs" as UC02
    usecase "UC03 - Register Collaborators" as UC03
    usecase "UC01 - Register skills" as UC01


    HRM --> UC01
    HRM --> UC02
    HRM --> UC03
    HRM --> UC04
    HRM --> UC05
    FM --> UC06
    FM --> UC07
    FM --> UC08
    GSM --> UC09
    GSM --> UC10
    GSM --> UC11
    GSM --> UC12
    GSM --> UC13
    QAM --> UC14
}


'note left of usecases
    'System
'end note

'note right of actors
'    Rectangles and Titles are for
'    demonstration purposes only.
'    Omitt on your diagrams.
'end note

@enduml