@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

actor "Human Resource Manager" as HRM
participant ":GenerateTeamUI" as UI
participant ":GenerateTeamController" as controller
participant ":Repositories" as singleton
participant "repositories\n:Repositories" as rep
participant "TeamRepository:\nTeamRepository" as teamRep
participant "Team" as Team

note right of singleton
    - Singleton is
    in use
end note

activate HRM

        HRM -> UI : asks to generate a team proposal

        activate UI
            'create controller
            UI -> controller** : create

            activate controller

                controller-> singleton : getInstance()

                activate singleton

                    singleton --> controller : repositories

                deactivate singleton

                controller -> rep : getEmployeeRepository()

                activate rep


                    rep --> controller : employeeRep

                deactivate rep




            'requests the HRM to input data
            UI --> HRM : requestData (team maximum size and minimum size)
        deactivate UI

        HRM -> UI : types requested data

activate UI

        activate rep

            controller -> rep : getSkillRepository()
            rep -> controller : skillRepository
        deactivate rep


            controller --> UI : getAllSkills()
            deactivate controller

loop
            UI --> HRM : shows list of skills and asks to select one

            HRM -> UI : selects skill
end
           UI -> controller : create Team
                   deactivate UI

            activate controller


                controller -> Team : Team

                activate Team

                Team --> controller : newTeam

                deactivate Team

                controller -> teamRep : add (newTeam )

                activate teamRep

                    teamRep -> teamRep : validateteam(newTeam)


                    teamRep --> controller : newTeam

                deactivate teamRep

            controller --> UI : newTeam


        deactivate controller
activate UI
        UI -> HRM : displays success operation

    deactivate UI

deactivate HRM

@enduml