@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false



'hide footbox


participant "repositories\n:Repositories" as PLAT
participant "authenticationRepository\n:AuthenticationRepository" as AUTH_REPO
participant "userSession\n:UserSessoin" as USR_SESSION



autonumber 6
-> PLAT : getEmployeeFromSession()

autonumber 6.1

activate PLAT
    PLAT -> PLAT : getAuthenticationRepository()

    PLAT -> AUTH_REPO : getCurrentUserSession()

    activate AUTH_REPO

        AUTH_REPO -> USR_SESSION : getUserId()

        activate USR_SESSION

            USR_SESSION --> AUTH_REPO : employee

        deactivate USR_SESSION

    AUTH_REPO -->PLAT : employee

    deactivate AUTH_REPO

    group Get Employee

    autonumber 7

 <-- PLAT: employee
deactivate PLAT

@enduml