@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class ListMyGreenSpacesUI {
    +run()
}

class CreateGreenSpacesController {
    - greenSpacesRepository:GreenSpacesRepository
    - authenticationRepository:AuthenticationRepository

    - getEmployeeFromSession()
    + getGreenSpacesManaged(String email)
}

class Manager{
    -name:String
    -birthdate:Date
    -admissionDate:Date
    -address
    -mobileContact:String
    -emailContact:String
    -IDdocType:String
    -IDnumber:String
    -taxNumber:String
    -job:Job

    +Manager (String nome,LocalDate dateOfBirth,\nLocalDate admissionDate, String morada, int telemovel,\nString email, String idDocType, int docTypeNumber,\nint taxPayerIdNumber, String role, Job job)
}

class Repositories{
    - instance: Repositories
    - managerRepository: ManagerRepository
    - authenticationRepository: AuthenticationRepository
    - greenSpacesRepository: GreenSpacesRepository

    + getInstance()
    + getManagerRepository()
    + getAuthenticationRepository()
    + getGreenSpacesRepository()
}

class GreenSpacesRepository{
    + getAllGreenSpaces()
    + getGreenSpacesManaged(String email)
    + validateGreenSpace(GreenSpace)
    + addGreenSpace(GreenSpace)
}

class AuthenticationRepository{
    + getEmployeeFromSession()
}

class GreenSpace {
    - String name
    - double area
    - String classification
    - Employee manager

    + GreenSpace(String name, double area, String classification, Employee manager)
}

interface SortAlgoritm {
}

ListMyGreenSpacesUI "1" ..> "1" CreateGreenSpacesController

CreateGreenSpacesController "1" --> "1" Repositories : getInstance
CreateGreenSpacesController --> Manager : listMyGreenSpaces

Repositories -> Repositories : instance
Repositories "1" ..> "1" GreenSpacesRepository : create
Repositories "1" --> "1" AuthenticationRepository : getCurrentUserSession

GreenSpacesRepository --> GreenSpace : have
GreenSpacesRepository --> SortAlgoritm : sortList

Manager --> Repositories : listMyGreenSpaces

@enduml