@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US08

autonumber

actor "GreenSpace\nManager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to add a team to an entry
    activate System

   System-->Employee: Show list of entries in the agenda

       Employee -> System: Selects an entry

       System --> Employee: Show list of teams created

       Employee -> System: Selects a team


       Alt Team available
           System --> Employee: Team assignment successful
           System -> Employee: Display success message with data selected
       End
       Alt Team unavailable
           System -> Employee: Team cannot be assigned (Already assigned in that hour range)
           Employee --> System: Select another team or exit
           System -> Employee : Displays operation confirmation message

       End
       deactivate System

@enduml