@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US08

autonumber

actor "Fleet\nManager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to create a list of the vehicles that need check-up
    activate System

        System --> Employee : selects data from the listed vehicles and presents the list
    deactivate System

@enduml